import * as CNSTS from '../modules/me/constant';
import * as BENEFITS_CONSTANTS from '../modules/benefits/constant';
import * as DOCTORS_CONSTANTS from '../modules/doctors/constant';

const paths = {
  common: {
    root: '/',
    appLink: '/app-link',
    default: '/',
    error: '/error',
    notfound: '/error/404',
    unauthorized: '/unauthorized',
    login: '/login',
    logout: '/logout',
    renewToken: '/renew-token',
    tokenExpired: '/unauthorized/token-expired',
    accountAcivation: '/account-activation',
    accountActivationError: '/account-activation/error',
    forgotPasswordSuccess: '/forgot-password/success',
    activationSuccess: '/activation/success',
    activationLinkExpired: '/activation/link-expired',
    forgotPassword: '/forgot-password',
    lifestyle: '/lifestyle',
    claims: '/claims',
    choices: '/choices',
    claimReview: '/claims/review',
    claimSuccess: '/claims/success',
    claimDetails: '/claims/claim-details',
    clinic: DOCTORS_CONSTANTS.FIND_DOCTOR_PATHNAME,
    questionnaire: '/lifestyle/questionnaire',
    onBoarding: '/on-boarding',
    onBoardingLinkExpired: '/on-boarding/link-expired',
    onBoardingSuccess: '/on-boarding/success',
    resetPassword: '/reset-password',
    resetPasswordSuccess: '/reset-password/success',
    resetPasswordLinkExpired: '/reset-password/link-expired',
    resetPasswordAccountLocked: '/reset-password/account-locked',
    privacy: '/legal/privacy',
    terms: '/legal/terms',
    contactUs: '/contact-us',
    [CNSTS.ME_ID]: CNSTS.ME_PATHNAME,
    [CNSTS.DETAILS_ID]: CNSTS.DETAILS_PATHNAME,
    [CNSTS.SETTINGS_ID]: CNSTS.SETTINGS_PATHNAME,
    [CNSTS.UPDATE_EMAIL_ID]: CNSTS.UPDATE_EMAIL_PATHNAME,
    [CNSTS.UPDATE_EMAIL_SUCCESS_ID]: CNSTS.UPDATE_EMAIL_SUCCESS_PATHNAME,
    verifyNewEmail: '/verify-new-email',
    verifyNewEmailLinkExpired: '/verify-new-email/link-expired',
    verifyNewEmailSuccess: '/verify-new-email/success',
    [CNSTS.RESEND_EMAIL_ID]: CNSTS.RESEND_EMAIL_PATHNAME,
    paymentPurchase: '/payment-purchase',
    paymentPurchaseResult: '/payment/payment-purchase-result',
    [BENEFITS_CONSTANTS.BENEFITS_ROOT_ID]:
      BENEFITS_CONSTANTS.BENEFITS_ROOT_PATHNAME,
    [BENEFITS_CONSTANTS.HEALTHCARDS_ID]:
      BENEFITS_CONSTANTS.HEALTHCARDS_PATHNAME,
    [BENEFITS_CONSTANTS.E_WALLET_ID]: BENEFITS_CONSTANTS.E_WALLET_PATHNAME,
    [BENEFITS_CONSTANTS.BENEFITS_ID]: BENEFITS_CONSTANTS.BENEFITS_PATHNAME,
    [BENEFITS_CONSTANTS.DOCUMENTS_ID]: BENEFITS_CONSTANTS.DOCUMENTS_PATHNAME,
    [BENEFITS_CONSTANTS.FAQ_ID]: BENEFITS_CONSTANTS.FAQ_PATHNAME,
    [DOCTORS_CONSTANTS.DOCTORS_ROOT_ID]:
      DOCTORS_CONSTANTS.DOCTORS_ROOT_PATHNAME,
    [DOCTORS_CONSTANTS.FIND_DOCTOR_ID]: DOCTORS_CONSTANTS.FIND_DOCTOR_PATHNAME,
    [DOCTORS_CONSTANTS.HEALTHCARDS_ID]: DOCTORS_CONSTANTS.HEALTHCARDS_PATHNAME,
    [CNSTS.UPDATE_MOBILE_NUMBER_ID]: CNSTS.UPDATE_MOBILE_NUMBER_PATHNAME,
    [CNSTS.VERIFY_OTP_ID]: CNSTS.VERIFY_OTP_PATHNAME,
    [CNSTS.VERIFY_OTP_SUCCESS_ID]: CNSTS.VERIFY_OTP_SUCCESS_PATHNAME,
    [CNSTS.VERIFY_OTP_MAX_ATTEMPTS_ID]: CNSTS.VERIFY_OTP_MAX_ATTEMPTS_PATHNAME,
  },
  employee: {
    makeClaim: '/claims/make-claim',
    [CNSTS.INVIDE_DEP_ID]: CNSTS.INVIDE_DEP_PATHNAME,
    [CNSTS.INVIDE_DEP_SUCCESS_ID]: CNSTS.INVIDE_DEP_SUCCESS_PATHNAME,
  },
  dependent: {},
  payment: {
    preauth: '/payment/preauth',
    preauthResult: '/payment/preauth-result',
    paymentShop: '/payment-shop',
    paymentShopResult: '/payment/payment-shop-result',
  },
};

export default paths;
