import { fork } from 'redux-saga/effects';

import { forgotPasswordSaga } from '../modules/login/forgot-password';
import { resetPasswordSaga } from '../modules/login/reset-password';
import { claimSaga } from '../modules/claims';
import { makeClaimSaga } from '../modules/claims/make-claim';
import { claimDetailsSaga } from '../modules/claims/claim-details';
import { meSaga } from '../modules/me';
import { inviteDependentSaga } from '../modules/me/details/invite';
import { settingsSaga } from '../modules/me/settings';
import { lifestyleSaga } from '../modules/lifestyle';
import { lifestyleTipsSaga } from '../modules/lifestyle/general-tips';
import { questionnaireSaga } from '../modules/lifestyle/questionnaire';
import { lifestyleResultsSaga } from '../modules/lifestyle/lifestyle-results';
import { lifestyleHealthScoresHistorySaga } from '../modules/lifestyle/lifestyle-history';
import { lifestyleScoreSaga } from '../modules/lifestyle/lifestyle-score';
import { faceAgingSaga } from '../modules/lifestyle/face-aging';
import { privacySaga } from '../modules/legal/privacy';
import { termsSaga } from '../modules/legal/terms';
import { paymentSaga } from '../modules/payment';
import { validateActivationSaga } from '../modules/login/activation';
import { newsLetterSaga } from '../modules/legal/newsletter';
import { miscSaga } from '../modules/misc';
import { recommendationsSaga } from '../modules/common/recommendations';
import { walletSaga } from '../modules/benefits/wallets';
import { usefulDocumentsSaga } from '../modules/benefits/documents';
import { helpSaga } from '../modules/benefits/help';
import { clinicSaga } from '../modules/doctors/clinic';
import { accountActivationSaga } from '../modules/login/account-activation';

export default function* rootSaga() {
  yield fork(forgotPasswordSaga);
  yield fork(resetPasswordSaga);
  yield fork(claimSaga);
  yield fork(makeClaimSaga);
  yield fork(claimDetailsSaga);
  yield fork(clinicSaga);
  yield fork(meSaga);
  yield fork(inviteDependentSaga);
  yield fork(settingsSaga);
  yield fork(lifestyleSaga);
  yield fork(lifestyleTipsSaga);
  yield fork(questionnaireSaga);
  yield fork(lifestyleResultsSaga);
  yield fork(lifestyleHealthScoresHistorySaga);
  yield fork(lifestyleScoreSaga);
  yield fork(faceAgingSaga);
  yield fork(privacySaga);
  yield fork(termsSaga);
  yield fork(paymentSaga);
  yield fork(validateActivationSaga);
  yield fork(newsLetterSaga);
  yield fork(miscSaga);
  yield fork(recommendationsSaga);
  yield fork(walletSaga);
  yield fork(usefulDocumentsSaga);
  yield fork(helpSaga);
  yield fork(accountActivationSaga);
}
