export const GET_INSTRUMENTS = 'GET_INSTRUMENTS';
export const VALIDATE_INSTRUMENT = 'VALIDATE_INSTRUMENT';
export const UPDATE_INSTRUMENTS = 'UPDATE_INSTRUMENTS';
export const SUBMIT_PRE_AUTH = 'SUBMIT_PRE_AUTH';
export const UPDATE_PAYMENT_PRE_AUTH = 'UPDATE_PAYMENT_PRE_AUTH';
export const VALIDATE_ORDER = 'VALIDATE_ORDER';
export const GET_PAYMENT_METHODS = 'GET_PAYMENT_METHODS';
export const UPDATE_PAYMENT_METHODS = 'UPDATE_PAYMENT_METHODS';
export const CHECK_OUT_ORDER = 'CHECK_OUT_ORDER';
export const GO_BACK = 'GO_BACK';
export const GET_PAYMENT_PURCHASE_METHODS = 'GET_PAYMENT_PURCHASE_METHODS';
export const UPDATE_PAYMENT_PURCHASE_METHODS =
  'UPDATE_PAYMENT_PURCHASE_METHODS';
export const MAKE_A_PAYMENT = 'MAKE_A_PAYMENT';
export const VALIDATE_PAYMENT = 'VALIDATE_PAYMENT';
export const GET_NOTE_TEXTS = 'GET_NOTE_TEXTS';
