apiVersion: v1
kind: Secret
metadata:
  name: distribution-employee-frontend
  namespace: prod
type: Opaque
stringData:
  GOOGLE_MAP_API_KEY: "${GOOGLE_MAP_API_KEY}"
  AUTH0_SSO_CLIENT_ID: "${AUTH0_SSO_CLIENT_ID}"
  AUTH0_SSO_CLIENT_SECRET: "${AUTH0_SSO_CLIENT_SECRET}"
  SENTRY_DSN: "${SENTRY_DSN}"
  COOKIE_SIGN_KEY: "${COOKIE_SIGN_KEY}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: distribution-employee-frontend
  namespace: prod
data:
  CLIENT_ID: "${CLIENT_ID}"
  DEFAULT_LANGUAGE: "en-HK"
  GOOGLE_MAP_API_KEY: ""
  BACKEND_SERVICE: "${BACKEND_SERVICE}"
  CLAIM_SERVICE: "http://distribution-claim-service:5000/"
  AUTH_SERVICE: "http://distribution-auth-service:5000/"
  PANEL_SERVICE: "http://distribution-panel-service:5000/"
  MEMBER_SERVICE: "http://distribution-member-service:5000/"
  BENEFIT_SERVICE: "http://distribution-benefit-service:5000/"
  WALLET_SERVICE: "http://distribution-wallet-service:5000/"
  E_WALLET_SERVICE: "${E_WALLET_SERVICE}"
  CONTENT_SERVICE: "http://distribution-content-service:5000/"
  WELLNESS_SERVICE: "http://distribution-wellness-service:5000/"
  RECOMMENDATION_SERVICE: "http://distribution-recommendation-service:5000/"
  PAYMENT_SERVICE: "http://distribution-payment-service:5000/"
  COGNITO_SERVICE: "http://distribution-auth-cognito-service:5000/"
  OL_SERVICE: "${OL_INTERNAL_URL}"
  ZUUL_SERVICE: "${auth0__protocol}${auth0__tenantUrl}"
  ETPA_SERVICE: "http://distribution-etpa-service:5000/"
  AUTH0_AUTHORIZE_URL: "${AUTH0_AUTHORIZE_URL}"
  AUTH0_LOGOUT_URL: "${AUTH0_LOGOUT_URL}"
  AUTH0_REDIRECT_URL: "${AUTH0_REDIRECT_URL}"
  AUTH0_CONNECTION: "${AUTH0_CONNECTION}"
  AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
  AUTH0_OAUTH_TOKEN_URL: "${AUTH0_OAUTH_TOKEN_URL}"
  AUTH0_CLIENT_ID: "${ClaimNameSpace__ClientId}"
  AUTH0_PENDING_ACTION: "${ClaimNameSpace__PendingAction}"
  SENTRY_DSN: ""
  SENTRY_ENV: "${SENTRY_ENV}"
  SENTRY_ORG: "${SENTRY_ORG}"
  SENTRY_PROJECT: "${SENTRY_PROJECT}"
  ENABLE_SENTRY_PAYMENT: "${ENABLE_SENTRY_PAYMENT}"

  APP_STORE_LINK: "${APP_STORE_LINK}"
  PLAY_STORE_LINK: "${PLAY_STORE_LINK}"
  SHOP_URL: "${SHOP_URL}"
  FEATURE_TOGGLE_LIFESTYLE: "${FEATURE_TOGGLE_LIFESTYLE}"
  FEATURE_TOGGLE_LIFESTYLE_SUGGESTIONS: "${FEATURE_TOGGLE_LIFESTYLE_SUGGESTIONS}"
  FEATURE_TOGGLE_CLUSTRED_MAP: "${FEATURE_TOGGLE_CLUSTRED_MAP}"
  MIN_SPOUSE_AGE: "18"
  MIN_CHILD_AGE: "18"
  MAX_CHILD_AGE: "23"
  ENVIRONMENT: "${ENVIRONMENT_NAME}"
  APP_VERSION_NAME: "1.0.0"
  WEB_FLAVOR: "${WEB_FLAVOR}"
  MASTER_CARD_SESSION: "${MASTER_CARD_SESSION}"
  FIREBASE_API_KEY: "${FIREBASE_API_KEY}"
  FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN}"
  FIREBASE_DATABASE_URL: "${FIREBASE_DATABASE_URL}"
  FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
  FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}"
  FIREBASE_MESSAGING_SENDER_ID: "${FIREBASE_MESSAGING_SENDER_ID}"
  FIREBASE_APP_ID: "${FIREBASE_APP_ID}"
  FIREBASE_MEASUREMENT_ID: "${FIREBASE_MEASUREMENT_ID}"
  ENABLE_GA: "${ENABLE_GA}"
  ENABLE_SHOP_API: "${ENABLE_SHOP_API}"
  SHOP_SERVICE: "${SHOP_SERVICE}"
  IOS_APP_ID: ${IOS_APP_ID}
  IOS_APP_PATHS: ${IOS_APP_PATHS}
  ANDROID_PACKAGE_NAME: ${ANDROID_PACKAGE_NAME}
  ANDROID_SHA256_CERT_FINGERPRINTS: ${ANDROID_SHA256_CERT_FINGERPRINTS}
  ENABLE_FEATURE_TOGGLE: "${ENABLE_FEATURE_TOGGLE}"
  PAYMENT_TERM_OF_USE_URL: "${PAYMENT_TERM_OF_USE_URL}"
  FEATURE_TOGGLE_KEY: "${FEATURE_TOGGLE_KEY}"
  PAYMENT_JWT_DURATION: "${PAYMENT_JWT_DURATION}"
  ENABLE_ETPA_SERVICE: "${ENABLE_ETPA_SERVICE}"
  USE_EXTERNAL_BENEFITS: "${USE_EXTERNAL_BENEFITS}"
  USE_CURRENCY_SYMBOL: "${USE_CURRENCY_SYMBOL}"
  FEATURE_TOGGLE_C2_5798_ENABLE_REFRESH_TOKEN: "${FEATURE_TOGGLE_C2_5798_ENABLE_REFRESH_TOKEN}"
  IDENTITY_CS_EMAIL: "${IDENTITY_CS_EMAIL}"
  FEATURE_TOGGLE_AWS_COGNITO: "${FEATURE_TOGGLE_C2_7684_UseAwsCognito}"
  AWS_COGNITO_EXCHANGE_TOKEN_URL: "${AWS_COGNITO_EXCHANGE_TOKEN_URL}"
  DISABLE_PENDING_ACTION: "${DISABLE_PENDING_ACTION}"
  THEME_CODE: "${THEME_CODE}"
  LOG_LEVEL: "${LOG_LEVEL}"
  USE_PRODUCT_NAME_FROM_CMS: "${USE_PRODUCT_NAME_FROM_CMS}"
  USE_LIFESTYLE_TIP_FROM_CMS: "${USE_LIFESTYLE_TIP_FROM_CMS}"
  SUPPORTED_LANGUAGES: "${SUPPORTED_LANGUAGES}"
